### ISSUE TITLE
Nice work! But need update =)

### ISSUE THREAD

**Issue by xeyz0r** [luyikk/RussianFishing4Reverse#1]
Can you give me your contacts? I have some ideas

**Comment by luyikk** [comment]
ok, but china epidemic situation,so it needs to be postponed




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xeyz0r"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月21日(星期二) 晚上10:33
收件人:&nbsp;"luyikk/RussianFishing4Reverse"<RussianFishing4Reverse@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[luyikk/RussianFishing4Reverse] Nice work! But need update =) (#1)




Can you give me your contacts? I have some ideas

**Comment by xeyz0r** [comment]
Are you okay? When can you do your mod? Ready to pay money!

**Comment by xeyz0r** [comment]
> ok, but china epidemic situation,so it needs to be postponed
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Xeyz0r"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月21日(星期二) 晚上10:33 收件人:&nbsp;"luyikk/RussianFishing4Reverse"<RussianFishing4Reverse@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[luyikk/RussianFishing4Reverse] Nice work! But need update =) (#1) Can you give me your contacts? I have some ideas — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Are you okay? When can you do your mod? Ready to pay money!
